import 'bootstrap/dist/css/bootstrap.min.css'
import 'font-awesome/css/font-awesome.min.css'
import 'admin-lte/dist/css/AdminLTE.min.css'
import 'admin-lte/dist/css/skins/_all-skins.css'
import '../assets/scss/main.scss'
import 'viewerjs/dist/viewer.css'
import 'mavon-editor/dist/css/index.css'
